### PR TITLE
Show descriptive messages on fail to read stdin

### LINKED ISSUE #57: `IN` trap triggers panic when `EOF` is reached
```asm
IN
```

```sh
printf | lace run hw.asm
```

```
thread 'main' panicked at src/runtime.rs:439:38:
called `Result::unwrap()` on an `Err` value: Error { kind: UnexpectedEof, message: "failed to fill whole buffer" }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

This is unfortunately an bug which I have introduced.

Possible solutions:

1. Block indefinitely (not sure how this could be useful with piped input).
2. Immediately halt / terminate the program.
3. Put some dummy value in `R0` (eg. `0`).
4. Don't modify `R0` (this seems dangerous).

I think 2. and 3. are the best solutions.

### PR DESCRIPTION
**Pull request by dxrcy**
When `read_input` fails, the panic message is now more descriptive than an anonymous `unwrap`.
Especially helpful for when non-terminal stdin reaches EOF.

Fixes #57.

### CODE REVIEW

File: src/runtime.rs [hunk 1]
```diff
@@ -1,7 +1,7 @@
 use std::{
     cmp::Ordering,
     i16,
-    io::{stdin, stdout, IsTerminal, Read, Write},
+    io::{self, stdin, stdout, IsTerminal, Read, Write},
```
Comment (rozukke) [inline src/runtime.rs:4]: This `self` does not seem correct

Comment (dxrcy) [reply src/runtime.rs:4]: Why not? It is used on line 442:
```rs
            if let io::ErrorKind::UnexpectedEof = err.kind() {
```

Comment (rozukke) [reply src/runtime.rs:4]: Mb eyes glazed over it

**Review by rozukke — APPROVED** [review]
